# Generated by Django 6.0.6 on 2026-06-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_setup_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='lead_qualification_questions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_hours',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='business',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='business',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='business',
            name='faqs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='business',
            name='service_areas',
            field=models.TextField(blank=True, help_text='Comma separated areas'),
        ),
        migrations.AlterField(
            model_name='business',
            name='services_offered',
            field=models.TextField(blank=True, help_text='Comma separated services'),
        ),
    ]
