# Generated by Django 6.0.6 on 2026-06-11 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_business_is_setup_complete_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='faqs',
        ),
        migrations.AlterField(
            model_name='business',
            name='appointment_rules',
            field=models.TextField(blank=True, help_text='e.g., "Must book 24h in advance", "Free cancellations up to 5h before"', null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_hours',
            field=models.JSONField(blank=True, default=dict, help_text='Format: {"Monday": "9am-5pm", "Saturday": "Closed"}'),
        ),
        migrations.AlterField(
            model_name='business',
            name='lead_qualification_questions',
            field=models.TextField(blank=True, help_text='e.g., "Are you the homeowner?", "How old is the current roof?"', null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='special_instructions',
            field=models.TextField(blank=True, help_text='Directives for the AI: e.g., "Always be cheerful", "Never give exact dates"', null=True),
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='businesses.business')),
            ],
        ),
    ]
