# Generated by Django 6.0.6 on 2026-06-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_remove_business_faqs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=128)),
                ('business_name', models.CharField(max_length=255)),
                ('business_description', models.TextField(help_text='Tell us about your business to get approved')),
                ('website_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
