# Generated by Django 6.0.6 on 2026-06-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_registrationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='ui_border_radius',
            field=models.CharField(default='12px', help_text='e.g., 12px, 0px, 1rem', max_length=10),
        ),
        migrations.AddField(
            model_name='business',
            name='ui_theme_color',
            field=models.CharField(default='#4f46e5', help_text='Hex color code for the chat header and buttons.', max_length=10),
        ),
    ]
