# Generated by Django 6.0.6 on 2026-06-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_business_ui_border_radius_business_ui_theme_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='ui_text_color',
            field=models.CharField(default='#ffffff', help_text='Hex color code for the text inside header and buttons.', max_length=10),
        ),
    ]
