# Generated by Django 6.0.6 on 2026-06-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_business_ui_text_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
