# Generated by Django 6.0.6 on 2026-06-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0007_alter_business_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='ui_banner_color',
            field=models.CharField(default='#f3f4f6', help_text='Hex color code for the banner/header section of the assistant page.', max_length=10),
        ),
    ]
