version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=nexflow_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-debug-key
      - DATABASE_URL=postgres://postgres:postgres@db:5432/nexflow_db
      - ALLOWED_HOSTS=localhost,127.0.0.1,web,13.61.225.84
    depends_on:
      - db

volumes:
  postgres_data:
